create table if not exists public.template (
  id varchar primary key,
  name varchar not null,
  original_pdf_path varchar not null,
  original_filename varchar not null,
  page_count integer not null,
  status varchar not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.templatepage (
  id bigint generated by default as identity primary key,
  template_id varchar not null references public.template(id) on delete cascade,
  page_number integer not null,
  source_page_number integer not null,
  width double precision not null,
  height double precision not null
);
create index if not exists ix_templatepage_template_id on public.templatepage(template_id);

create table if not exists public.templatetextelement (
  id varchar primary key,
  template_id varchar not null references public.template(id) on delete cascade,
  page_number integer not null,
  content varchar not null,
  x double precision not null,
  y double precision not null,
  width double precision not null,
  height double precision not null,
  font_family varchar not null default 'helvetica',
  font_size double precision not null default 24,
  font_weight varchar not null default '400',
  font_style varchar not null default 'normal',
  is_bold boolean not null default false,
  is_italic boolean not null default false,
  is_underline boolean not null default false,
  is_strikethrough boolean not null default false,
  text_color varchar not null default '#111827',
  background_color varchar,
  text_opacity double precision not null default 1,
  background_opacity double precision not null default 0,
  text_align varchar not null default 'left',
  vertical_align varchar not null default 'top',
  line_height double precision not null default 1.2,
  letter_spacing double precision not null default 0,
  word_spacing double precision not null default 0,
  text_transform varchar not null default 'none',
  padding_top double precision not null default 0,
  padding_right double precision not null default 0,
  padding_bottom double precision not null default 0,
  padding_left double precision not null default 0,
  border_width double precision not null default 0,
  border_color varchar not null default '#000000',
  border_style varchar not null default 'solid',
  border_radius double precision not null default 0,
  rotation double precision not null default 0,
  z_index integer not null default 0,
  locked boolean not null default false,
  auto_shrink boolean not null default false,
  clip_overflow boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists ix_templatetextelement_template_id on public.templatetextelement(template_id);

create table if not exists public.templatevariable (
  id bigint generated by default as identity primary key,
  template_id varchar not null references public.template(id) on delete cascade,
  name varchar not null,
  label varchar not null,
  type varchar not null default 'text',
  required boolean not null default true,
  default_value varchar,
  sample_value varchar,
  description varchar,
  generator_enabled boolean not null default false,
  generator_pattern varchar,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists ix_templatevariable_template_id on public.templatevariable(template_id);
create index if not exists ix_templatevariable_name on public.templatevariable(name);

create table if not exists public.generateddocument (
  id varchar primary key,
  template_id varchar not null references public.template(id) on delete cascade,
  data_json varchar not null,
  generated_pdf_path varchar not null,
  created_at timestamptz not null default now()
);
create index if not exists ix_generateddocument_template_id on public.generateddocument(template_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'templates',
  'templates',
  false,
  52428800,
  array['application/pdf', 'application/zip', 'application/octet-stream']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
